#!/usr/bin/env ruby

BASE = File.dirname(__FILE__)

File.open(BASE + '/slick.js', 'w') do |file|
  
  file << File.read(BASE + '/Slick.Parser.js')
  file << File.read(BASE + '/Slick.Finder.js')
  
end
